services:
  postgres:
    image: postgres
    container_name: todo_postgres
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: ToDoListApp
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5
      timeout: 3s

  backend:
    build: ./todo-list-backend
    container_name: todo_backend
    ports:
      - 3000:3000
    depends_on:
      postgres:
        condition: service_healthy  # Ensures database is fully ready
    environment:
      DATABASE_URL: postgres://postgres:12345@postgres:5432/ToDoListApp
    command: sh -c "sleep 5 && npm run start:dev"  # Extra delay to ensure DB is fully ready
    volumes:
      - ./backend:/app
      - /app/node_modules
    restart: unless-stopped

  frontend:
    build: ./todo-list-frontend
    container_name: todo_frontend
    ports:
      - 5173:5173
    depends_on:
      backend:
        condition: service_started  # Ensures backend is up before frontend starts
    command: npm run dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      REACT_APP_API_URL: http://localhost:5173
    restart: unless-stopped

volumes:
  postgres_data:
