services:
  postgres:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: ToDoListApp
    restart: always

  backend:
    build:
      context: ./todo-list-backend  # Ensure this folder exists and contains a Dockerfile
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Change if your backend uses a different port
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:12345@postgres:5432/ToDoListApp
    restart: always

  frontend:
    build:
      context: ./todo-list-frontend  # Ensure this folder exists and contains a Dockerfile
      dockerfile: Dockerfile
    ports:
      - "5173:5173"  # Change if your frontend uses a different port
    depends_on:
      - backend
    restart: always
