services:
  postgres:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: ToDoListApp
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persistent storage for DB
    restart: always

  backend:
    build:
      context: ./todo-list-backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:12345@postgres:5432/ToDoListApp
    restart: always

  frontend:
    build:
      context: ./todo-list-frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend
    restart: always

volumes:
  postgres_data:  # Defines the persistent volume
