version: '3.8'

services:
  postgres:
    image: postgres

    # Maps port 5433 inside the container to port 5434 on your host machine:
    ports:
      - "5434:5433"

    # Loads environment variables from the .env file:
    env_file:
      - .env

    # Defines environment variables inside the container:
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}

    # Attaches a volume (postgres_data) to store PostgreSQL data persistently, 
    # so data remains even if the container is restarted.
    volumes:
      - postgres_data:/var/lib/postgresql/data

    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    ports:
      - "5000:5000"

    # Ensures that the postgres service starts before backend
    depends_on:
      - postgres

    env_file:
      - .env
    
    command: sh -c "npm install && npx drizzle-kit push && npm run start:dev"

    restart: always

#   frontend:
#     build:
#       context: ./frontend
#       dockerfile: Dockerfile

#     # Exposes port 5173 (default for Vite/React development servers).
#     ports:
#       - "5173:5173"

#     depends_on:
#       - backend

#     restart: always

volumes:
  postgres_data:
